name: azimuth
adopt-info: azimuth
summary: Azimuth - A metroidvania with vector graphics 
base: core20
description: |
  Azimuth is a metroidvania game, with vector graphics. Azimuth is inspired by such 
  games as the Metroid series (particularly Super Metroid and Metroid Fusion),
  SketchFighter 4000 Alpha, and Star Control II (a.k.a. The Ur-Quan Masters).
  All fine games that are well worth your time.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

parts:
  alsa-pulseaudio:
    plugin: dump
    source: .
    override-pull: |
      mkdir etc -p
      cat > etc/asound.conf <<EOF
      pcm.!default {
          type pulse
          fallback "sysdefault"
          hint {
              show on
              description "Default ALSA Output (currently PulseAudio Sound Server)"
          }
      }
      ctl.!default {
          type pulse
          fallback "sysdefault"
      }
      EOF
  azimuth:
    after: [alsa-pulseaudio]
    plugin: make
    source: https://github.com/mdsteele/azimuth.git
    override-build: |
      BUILDTYPE=release make
      cp out/release/host/Azimuth $SNAPCRAFT_PART_INSTALL
      snapcraftctl set-version $(git -C ../src describe --tags  | sed 's/v//')
    build-packages:
      - libsdl2-dev
      - libgl1-mesa-dev
    stage-packages:
      - libsdl2-2.0-0
      - libpulse0
      - libasan5
      - libglu1-mesa
      - freeglut3
      - libasyncns0
      - libogg0
      - libsndfile1
      - libxau6
      - libxcb1
      - libxdmcp6


apps:
  azimuth:
    extensions: [ gnome-3-38 ]
    environment:
      ALSA_CONFIG_PATH: "$SNAP/etc/asound.conf"
      SHELL: bash
      LC_ALL: C.UTF-8
      SNAPCRAFT_ARCH_TRIPLET: ${SNAPCRAFT_ARCH_TRIPLET}
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
      LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
      LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      HOME: "$SNAP_USER_DATA"
      XDG_CACHE_HOME: "$SNAP_USER_DATA/.cache" 
    command: Azimuth
    plugs:
      - x11
      - audio-playback
      - desktop
      - desktop-legacy
      - opengl
      - screen-inhibit-control
