name: azimuth
adopt-info: azimuth
summary: Azimuth - A metroidvania with vector graphics
base: core24
description: |
  Azimuth is a metroidvania game, with vector graphics. Azimuth is inspired by such
  games as the Metroid series (particularly Super Metroid and Metroid Fusion),
  SketchFighter 4000 Alpha, and Star Control II (a.k.a. The Ur-Quan Masters).
  All fine games that are well worth your time.

grade: stable
confinement: strict

platforms:
  amd64:
  arm64:
  armhf:

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib

parts:
  alsa-pulseaudio:
    plugin: dump
    source: .
    override-pull: |
      mkdir etc -p
      cat > etc/asound.conf <<EOF
      pcm.!default {
          type pulse
          fallback "sysdefault"
          hint {
              show on
              description "Default ALSA Output (currently PulseAudio Sound Server)"
          }
      }
      ctl.!default {
          type pulse
          fallback "sysdefault"
      }
      EOF
  azimuth:
    after: [alsa-pulseaudio]
    plugin: make
    source: https://github.com/mdsteele/azimuth.git
    override-build: |
      sed -i 's/-Werror//g' Makefile
      BUILDTYPE=release make
      patchelf --clear-execstack out/release/host/Azimuth
      cp out/release/host/Azimuth $CRAFT_PART_INSTALL
      craftctl set version=$(git -C ../src for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+)?$' | head -n 1)
    build-packages:
      - libsdl2-dev
      - libgl1-mesa-dev
      - patchelf
    stage-packages:
      - libsdl2-2.0-0
      - libpulse0
      - libglu1-mesa
      - libglut3.12
      - libasyncns0
      - libogg0
      - libsndfile1
      - libxau6
      - libxcb1
      - libxdmcp6

apps:
  azimuth:
    extensions: [ gnome ]
    environment:
      ALSA_CONFIG_PATH: "$SNAP/etc/asound.conf"
      SHELL: bash
      LC_ALL: C.UTF-8
      HOME: "$SNAP_USER_DATA"
      XDG_CACHE_HOME: "$SNAP_USER_DATA/.cache"
    command: Azimuth
    plugs:
      - x11
      - audio-playback
      - desktop
      - desktop-legacy
      - opengl
      - screen-inhibit-control
