name: azimuth
adopt-info: azimuth
summary: Azimuth - A metroidvania with vector graphics 
base: core18
description: |
  Azimuth is a metroidvania game, with vector graphics. Azimuth is inspired by such 
  games as the Metroid series (particularly Super Metroid and Metroid Fusion),
  SketchFighter 4000 Alpha, and Star Control II (a.k.a. The Ur-Quan Masters).
  All fine games that are well worth your time.

grade: stable
confinement: strict

parts:
  azimuth:
    plugin: make
    source: https://github.com/mdsteele/azimuth.git
    override-build: |
      make
      cp out/debug/host/Azimuth $SNAPCRAFT_PART_INSTALL
      snapcraftctl set-version $(git -C ../src describe --tags  | sed 's/v//')      
    build-packages:
      - libsdl1.2-dev
      - libgl1-mesa-dev
    stage-packages:
      - libglu1-mesa
      - libsdl1.2debian
      - libpulse0
      - libslang2
      - libasan4
      - freeglut3

apps:
  azimuth:
    environment:
      SHELL: bash
      LC_ALL: C.UTF-8
      SNAPCRAFT_ARCH_TRIPLET: ${SNAPCRAFT_ARCH_TRIPLET}
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
      LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
      LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      HOME: "$SNAP_USER_DATA"
      XDG_CACHE_HOME: "$SNAP_USER_DATA/.cache" 
    command: Azimuth
    plugs:
      - x11
      - pulseaudio
      - opengl
      - screen-inhibit-control
